CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    SURNAME VARCHAR(256) NOT NULL,
    AGE TINYINT
);

CREATE TABLE IF NOT EXISTS CONTACTS (
    ID INT PRIMARY KEY,
    ID_CUSTOMER INT NOT NULL,
    TYPE TINYINT NOT NULL,
    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID)
);